---
- name: Patch Ubuntu container
  hosts: all
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist
    - name: install httpd
      apt:
        name: apache2
        state: present
    - name: start httpd
      service:
        name: apache2
        state: started
    - name: create file
      file:
        path: /root/annsible
        state: touch 
    - name:insert content
      copy: 
        dest: /var/www/html/index.html
        content: "<h1> how </h1>"
    - name: restart container
      service:
          name: apache2
          state: restarted       
