---
- name: Patch Ubuntu container
  hosts: ubuntu_container
  become: true
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist

