- name: Patch Ubuntu container
  hosts: all
  become: yes
  tasks:
    - name: Install ntpdate for time sync
      apt:
        name: ntpdate
        state: present

    - name: Synchronize system time
      command: ntpdate -u ntp.ubuntu.com

    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install apache2
      apt:
        name: apache2
        state: present

    - name: Start apache2 service
      service:
        name: apache2
        state: started

    - name: Create file /root/ansible
      file:
        path: /root/ansible
        state: touch

    - name: Insert content into index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1> how </h1>"

    - name: Restart apache2
      service:
        name: apache2
        state: restarted

