---
- name: Patch Ubuntu container
  hosts: all
  become: yes
  tasks:
    - name: Update APT cache
      apt:
        update_cache: yes

    - name: Upgrade all packages
      apt:
        upgrade: dist

    - name: Install Apache (httpd)
      apt:
        name: apache2
        state: present

    - name: Start Apache service
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create file /root/annsible
      file:
        path: /root/annsible
        state: touch

    - name: Insert content into index.html
      copy:
        dest: /var/www/html/index.html
        content: "<h1> how </h1>"

    - name: Restart Apache
      service:
        name: apache2
        state: restarted

